// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehicleBooking.Web.Data;

#nullable disable

namespace VehicleSmartBooking.Migrations
{
    [DbContext(typeof(VehicleBookingDbContext))]
    partial class VehicleBookingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BookingId"));

                    b.Property<int?>("AssignedDriverId")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedVehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("CostCenter")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("DestinationLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DetailNote")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<bool>("IsExternalRental")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsPersonal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("JobNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<string>("PickupLocation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Purpose")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RequesterPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<string>("SONo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("StartAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<int>("TripType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("VehicleTypeRequested")
                        .HasColumnType("int");

                    b.HasKey("BookingId");

                    b.HasIndex("AssignedDriverId");

                    b.HasIndex("AssignedVehicleId");

                    b.HasIndex("RequesterUserId", "Status")
                        .HasDatabaseName("IX_Bookings_Requester_Status");

                    b.HasIndex("StartAtUtc", "EndAtUtc")
                        .HasDatabaseName("IX_Bookings_TimeRange");

                    b.ToTable("Bookings", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Bookings_Time", "[EndAtUtc] > [StartAtUtc]");
                        });
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.BookingApproval", b =>
                {
                    b.Property<long>("ApprovalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ApprovalId"));

                    b.Property<DateTime?>("ActionAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("LevelNo")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("ApprovalId");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("BookingId", "LevelNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Approvals_Booking_Level");

                    b.ToTable("BookingApprovals", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.BookingAttachment", b =>
                {
                    b.Property<long>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("AttachmentId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("UploadedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("UploadedByUserId")
                        .HasColumnType("int");

                    b.HasKey("AttachmentId");

                    b.HasIndex("BookingId")
                        .HasDatabaseName("IX_Attachments_Booking");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("BookingAttachments", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.BookingDispatchLog", b =>
                {
                    b.Property<long>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("LogId"));

                    b.Property<int>("AttemptNo")
                        .HasColumnType("int");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("DispatchedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int?>("DriverAction")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DriverActionAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("LogId");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("BookingId", "AttemptNo")
                        .IsUnique()
                        .HasDatabaseName("UX_DispatchLogs_Attempt");

                    b.ToTable("BookingDispatchLogs", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.Driver", b =>
                {
                    b.Property<int>("DriverId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DriverId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastAssignedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("DriverId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UX_Drivers_UserId");

                    b.HasIndex("VehicleId")
                        .IsUnique()
                        .HasDatabaseName("UX_Drivers_VehicleId");

                    b.ToTable("Drivers", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.DriverRating", b =>
                {
                    b.Property<long>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RatingId"));

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("Score1")
                        .HasColumnType("int");

                    b.Property<int>("Score2")
                        .HasColumnType("int");

                    b.Property<int>("Score3")
                        .HasColumnType("int");

                    b.Property<int>("Score4")
                        .HasColumnType("int");

                    b.Property<int>("Score5")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UX_Ratings_Booking");

                    b.HasIndex("DriverId");

                    b.ToTable("DriverRatings", "dbo", t =>
                        {
                            t.HasCheckConstraint("CK_Ratings_Score1", "[Score1] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_Ratings_Score2", "[Score2] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_Ratings_Score3", "[Score3] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_Ratings_Score4", "[Score4] BETWEEN 1 AND 4");

                            t.HasCheckConstraint("CK_Ratings_Score5", "[Score5] BETWEEN 1 AND 4");
                        });
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.ExternalRental", b =>
                {
                    b.Property<long>("ExternalRentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ExternalRentalId"));

                    b.Property<DateTime?>("AdminClosedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("QuoteSentAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<decimal?>("QuotedPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RentalDriverName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RentalDriverPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("RentalPlateNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserDecision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime?>("UserDecisionAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("VendorName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ExternalRentalId");

                    b.HasIndex("BookingId")
                        .IsUnique()
                        .HasDatabaseName("UX_ExternalRentals_Booking");

                    b.ToTable("ExternalRentals", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("DeptAbbr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DeptEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DeptTH")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DivAbbr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DivEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DivTH")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FunctionAbbr")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FunctionEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("FunctionTH")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int?>("LineManagerId")
                        .HasColumnType("int");

                    b.Property<string>("PositionEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PositionTH")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("RoleFlags")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<string>("UserCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UsernameEN")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("UsernameTH")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("DeptAbbr")
                        .HasDatabaseName("IX_Users_DeptAbbr");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("LineManagerId");

                    b.HasIndex("UserCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_UserCode");

                    b.ToTable("Users", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.UserCredential", b =>
                {
                    b.Property<int>("CredentialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CredentialId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("FailedCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsLocked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("Iterations")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(600000);

                    b.Property<DateTime?>("LastFailedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<string>("LoginUsername")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordAlgo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("PBKDF2-HMACSHA256");

                    b.Property<DateTime?>("PasswordChangedAtUtc")
                        .HasColumnType("datetime2(0)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(256)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(128)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CredentialId");

                    b.HasIndex("LoginUsername")
                        .IsUnique()
                        .HasDatabaseName("UX_UserCredentials_LoginUsername");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("UQ_UserCredentials_User");

                    b.ToTable("UserCredentials", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("PlateNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<DateTime>("UpdatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2(0)")
                        .HasDefaultValueSql("sysutcdatetime()");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("PlateNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Vehicles_PlateNo");

                    b.HasIndex("VehicleType", "Status")
                        .HasDatabaseName("IX_Vehicles_TypeStatus");

                    b.ToTable("Vehicles", "dbo");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.Booking", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.Driver", "AssignedDriver")
                        .WithMany()
                        .HasForeignKey("AssignedDriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleBooking.Web.Domain.Entities.Vehicle", "AssignedVehicle")
                        .WithMany()
                        .HasForeignKey("AssignedVehicleId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VehicleBooking.Web.Domain.Entities.User", "Requester")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedDriver");

                    b.Navigation("AssignedVehicle");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.BookingApproval", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleBooking.Web.Domain.Entities.Booking", "Booking")
                        .WithMany("Approvals")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Approver");

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.BookingAttachment", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.Booking", "Booking")
                        .WithMany("Attachments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleBooking.Web.Domain.Entities.User", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.BookingDispatchLog", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.Booking", "Booking")
                        .WithMany("DispatchLogs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleBooking.Web.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleBooking.Web.Domain.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Driver");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.Driver", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.User", "User")
                        .WithOne("DriverProfile")
                        .HasForeignKey("VehicleBooking.Web.Domain.Entities.Driver", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VehicleBooking.Web.Domain.Entities.Vehicle", "Vehicle")
                        .WithOne("Driver")
                        .HasForeignKey("VehicleBooking.Web.Domain.Entities.Driver", "VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.DriverRating", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.Booking", "Booking")
                        .WithOne("Rating")
                        .HasForeignKey("VehicleBooking.Web.Domain.Entities.DriverRating", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VehicleBooking.Web.Domain.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.ExternalRental", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.Booking", "Booking")
                        .WithOne("ExternalRental")
                        .HasForeignKey("VehicleBooking.Web.Domain.Entities.ExternalRental", "BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.User", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.User", "LineManager")
                        .WithMany("DirectReports")
                        .HasForeignKey("LineManagerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("LineManager");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.UserCredential", b =>
                {
                    b.HasOne("VehicleBooking.Web.Domain.Entities.User", "User")
                        .WithOne("Credential")
                        .HasForeignKey("VehicleBooking.Web.Domain.Entities.UserCredential", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.Booking", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Attachments");

                    b.Navigation("DispatchLogs");

                    b.Navigation("ExternalRental");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.User", b =>
                {
                    b.Navigation("Credential");

                    b.Navigation("DirectReports");

                    b.Navigation("DriverProfile");
                });

            modelBuilder.Entity("VehicleBooking.Web.Domain.Entities.Vehicle", b =>
                {
                    b.Navigation("Driver");
                });
#pragma warning restore 612, 618
        }
    }
}
